backend:
  name: github
  branch: main
  repo: yousef-milexa/Gatsby-practice

media_folder: "static/assets"
public_folder: assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    slug: "{{year}}--{{month}}--{{day}}--{{slug}}"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Slug", name: "slug", widget: "string" }
      - {
          label: "Post Image",
          name: "featuredImage",
          widget: "image",
          allow_multiple: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }  
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post" }
      - { label: "Body", name: "body", widget: "markdown" }    
  # - name: "pages"
  #   label: "Pages"
  #   files:
  #     - file: "src/pages/index.md"
  #       label: "Landing Page"
  #       name: "index"
  #       fields:
  #         - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
  #         - {label: Title, name: title, widget: string}
  #         - {label: Subheading, name: subheading, widget: string}
  #     - file: "src/pages/about/index.md"
  #       label: "About"
  #       name: "about"
  #       fields:
  #         - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
  #         - {label: "Title", name: "title", widget: "string"}
  #         - {label: "Body", name: "body", widget: "markdown"}